# Generated by Django 6.0.2 on 2026-07-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('next_move', models.TextField(max_length=128)),
                ('action_status', models.CharField(max_length=32)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('individual', 'Individual'), ('manager', 'Manager'), ('quorum', 'Quorum'), ('admin', 'Admin')], max_length=20)),
                ('name', models.CharField(max_length=16)),
                ('grade', models.CharField(max_length=16)),
                ('position', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=16)),
                ('history', models.TextField(max_length=256)),
                ('capabilities_and_attributes', models.TextField(max_length=256)),
                ('career_aspiractions', models.TextField(max_length=256)),
                ('development_needs', models.TextField(max_length=256)),
                ('mobility', models.TextField(max_length=128)),
                ('succession_plan', models.TextField(max_length=256)),
                ('successor', models.CharField(max_length=32)),
                ('potential_grade', models.CharField(max_length=16)),
                ('dev_cell_rating', models.CharField(max_length=16)),
                ('performance_rating', models.CharField(max_length=16)),
                ('wants', models.TextField(max_length=256)),
                ('needs', models.TextField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('manager', 'Manager'), ('mentor', 'Mentor')], max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_information', models.TextField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
